### ISSUE TITLE
Create a release procedure and deploy app to Rinkeby

### ISSUE THREAD

**Issue by macor161** [macor161/aragon-drive-app#70]
As part of our beta release, we should publish and install our app to Rinkeby. It would be great to document our process while we're at it.

If it's not possible to deploy to Rinkeby, the app could be published to a devchain on our personal server.

**Comment by juslar** [comment]
Aragon CLI doc is missing some informations. I searched on Aragon Chat and found this command:

`aragon apm publish minor --environment rinkeby`

Seems to be that simple :)

**Comment by macor161** [comment]
Done
