### ISSUE TITLE
Remove private file support in UI

### ISSUE THREAD

**Issue by macor161** [macor161/aragon-drive-app#84]
Public checkbox should be checked by default and users should not be able to uncheck it.

**Comment by juslar** [comment]
Personally, I would remove it completely as it could be confusing for the user. It would look cleaner too for now. We can create a separate branch with no private file support at all (for aragon-datastore too). What do you think?

**Comment by macor161** [comment]
Totally agree!

**Comment by macor161** [comment]
Done
